services:
  boxmgr:
    platform: linux/amd64
    build:
      context: . # Build the image from the Dockerfile in the current directory
      dockerfile: Dockerfile
    ports:
      - "4540:4540"
    volumes:
      - "../files/data:/app/data"
    container_name: boxmgr-app # Assign a specific name to the container
    restart: unless-stopped # Automatically restart the container unless it was manually stopped 
